### ISSUE TITLE
Problem launching MeGit both on Windows and Linux

### ISSUE THREAD

**Issue by fabiano-pereira** [eclipsesource/megit#15]
The following exception is happening when I try to launch MeGit 0.0.3 on Windows, a similar exception also happens on Linux. The whole log file has more exceptions, but this one is the first to appear.

```
!ENTRY com.eclipsesource.megit.plugin 4 0 2021-06-22 10:52:15.604
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: com.eclipsesource.megit.plugin [3]
  Unresolved requirement: Require-Bundle: org.eclipse.e4.ui.workbench
    -> Bundle-SymbolicName: org.eclipse.e4.ui.workbench; bundle-version="1.12.100.v20210122-1731"; singleton:="true"
       org.eclipse.e4.ui.workbench [85]
         Unresolved requirement: Require-Bundle: org.eclipse.e4.core.commands; bundle-version="0.11.100"
           -> Bundle-SymbolicName: org.eclipse.e4.core.commands; bundle-version="0.13.0.v20201119-1132"; singleton:="true"
              org.eclipse.e4.core.commands [66]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
         Unresolved requirement: Require-Bundle: org.eclipse.e4.ui.services; bundle-version="0.9.0"
           -> Bundle-SymbolicName: org.eclipse.e4.ui.services; bundle-version="1.5.0.v20210115-1333"; singleton:="true"
              org.eclipse.e4.ui.services [82]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
  Unresolved requirement: Require-Bundle: org.eclipse.ui
    -> Bundle-SymbolicName: org.eclipse.ui; bundle-version="3.119.0.v20210111-1350"; singleton:="true"
       org.eclipse.ui [195]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
         Unresolved requirement: Require-Bundle: org.eclipse.ui.workbench; bundle-version="[3.120.0,4.0.0)"; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.ui.workbench; bundle-version="3.122.100.v20210215-1525"; singleton:="true"
              org.eclipse.ui.workbench [217]
                Unresolved requirement: Import-Package: org.eclipse.e4.core.commands.internal
                  -> Export-Package: org.eclipse.e4.core.commands.internal; bundle-symbolic-name="org.eclipse.e4.core.commands"; bundle-version="0.13.0.v20201119-1132"; version="0.0.0"; x-friends:="org.eclipse.e4.ui.bindings,org.eclipse.ui.workbench"
                Unresolved requirement: Import-Package: org.eclipse.e4.core.commands
                  -> Export-Package: org.eclipse.e4.core.commands; bundle-symbolic-name="org.eclipse.e4.core.commands"; bundle-version="0.13.0.v20201119-1132"; version="0.0.0"; x-friends:="org.eclipse.e4.ui.bindings,  org.eclipse.e4.ui.workbench,  org.eclipse.e4.ui.workbench.renderers.swt,  org.eclipse.ui.workbench,  org.eclipse.e4.ui.workbench.swt,  org.eclipse.e4.ui.progress,  org.eclipse.e4.core.commands.tests"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

```

**Comment by planger** [comment]
Hi @fabiano-pereira, I can't reproduce this problem on Linux (Ubuntu). Can you please try if it is still reproducible with the latest release? Thanks!

**Comment by fabiano-pereira** [comment]
> Hi @fabiano-pereira, I can't reproduce this problem on Linux (Ubuntu). Can you please try if it is still reproducible with the latest release? Thanks!

A have installed the latest JDK and now it works fine, thanks.
