### ISSUE TITLE
Can't launch Megit on Windows 10 even after update of java

### ISSUE THREAD

**Issue by sindzicat** [eclipsesource/megit#17]
```
!SESSION 2021-12-25 19:30:52.272 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_311
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ru_RU
Framework arguments:  -pluginCustomization plugin_customization.ini -cssTheme org.eclipse.e4.ui.css.theme.e4_dark
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -pluginCustomization plugin_customization.ini -cssTheme org.eclipse.e4.ui.css.theme.e4_dark

!ENTRY org.eclipse.equinox.simpleconfigurator 4 0 2021-12-25 19:30:53.437
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.equinox.simpleconfigurator [2]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.lambda$1(ModuleContainer.java:1834)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1829)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1777)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1739)
	at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:269)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:193)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:439)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:458)
	at org.eclipse.osgi.launch.Equinox.start(Equinox.java:139)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:338)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

!ENTRY org.eclipse.osgi 4 0 2021-12-25 19:30:53.437
!MESSAGE Bundle initial@reference:file:plugins/org.eclipse.equinox.simpleconfigurator_1.4.0.v20210315-2228.jar was not resolved.

!ENTRY org.eclipse.equinox.simpleconfigurator 2 0 2021-12-25 19:30:53.437
!MESSAGE Could not resolve module: org.eclipse.equinox.simpleconfigurator [2]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"


!ENTRY org.eclipse.osgi 4 0 2021-12-25 19:30:53.437
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:81)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

**Comment by planger** [comment]
I'm sorry that you experience issues starting the application! On Linux, I can't reproduce this issue.

An error message like this usually means that either the config.ini is broken or jars are corrupted. Maybe the build is broken (I can't test this directly on Windows at the moment). But often it is also caused by corrupted extraction or pre-existing configs in the user home.

Can you please make sure that the extraction of the archive went smoothly? On Windows, I already observed that the archive extraction creates corrupt files if the paths get too long or if you use the Windows explorer to extract the archive. Please try extracting into a folder that is closer to the root of the disk and avoid using the Windows archiving tool, but use 7z.
If that doesn't help, can you please check if you have a .eclipse folder in your user home and retry after deleting (or temporarily renaming) it?

Thanks!

**Comment by sindzicat** [comment]
I downloaded from releases via aria2c and unpacked archive into `C:\\Apps` folder via 7zip archiver. But still cann't make this app to start. So I just will keep in mind that it's for Linux mainly. Thanks.

**Comment by saierd** [comment]
I had the same problem on Linux. It was caused by using (Oracle) Java 8 (which is not supported as stated in the readme). When I switched to OpenJDK 11 everything worked.

**Comment by sindzicat** [comment]
@saierd, thanks a lot. I downloaded OpenJDK 11 with OpenJ9 JVM from [here](https://adoptopenjdk.net/installation.html?variant=openjdk11&jvmVariant=openj9#x64_win-jdk), unpacked zip archive and add `bin`  folder with `java.exe` to the `PATH` variable. After this I could run megit.

**Comment by planger** [comment]
Thanks @saierd for the hint and great @sindzicat that it works now. I interpreted the title "even after update of java" that you are using an appropriate JRE for Java 11 already.
In the readme, we mention that we require at least Java 11.
Which JRE did you use before, when it was still failing? I'm asking, because maybe we should be more specific in the readme. On the Eclipse wiki, [it is just mentioned](https://wiki.eclipse.org/Eclipse/Installation) that a Java 11 JRE is required (as we mention in the readme of Megit). However, they also list a few sources for a JRE, such as AdoptOpenJDK, IBM JDK, OpenJDK, and Oracle JDK. Maybe we should do the same.

**Comment by sindzicat** [comment]
@planger, I used Java from Oracle before: https://www.java.com/en/download/

```
λ java -version
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)
```

**Comment by planger** [comment]
Ok thanks!
This is 1.8 (Java 8) though, so this JRE is known not to work with any Eclipse. So I guess the readme is accurate enough then.
